DROP TABLE staedte;


-- Aufgabe 1a)
CREATE TABLE staedte (
    stadt_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stadtname VARCHAR2(100), -- Name der Stadt
    breitengrad NUMBER(10,6) NOT NULL,   -- Einheit: Grad (° Nord/Süd)
    laengengrad NUMBER(10,6) NOT NULL    -- Einheit: Grad (° Ost/West)
);

--Aufgabe 1b)
BEGIN
    INSERT INTO staedte (stadtname, breitengrad, laengengrad) 
    VALUES ('Aachen', 50.775278, 6.083889);

    INSERT INTO staedte (stadtname, breitengrad, laengengrad) 
    VALUES ('Bonn', 50.733992, 7.099814);

    INSERT INTO staedte (stadtname, breitengrad, laengengrad) 
    VALUES ('Düsseldorf', 51.225556, 6.782778);

    INSERT INTO staedte (stadtname, breitengrad, laengengrad) 
    VALUES ('Duisburg', 51.2277, 6.7735);

    INSERT INTO staedte (stadtname, breitengrad, laengengrad) 
    VALUES ('Essen', 51.458069, 7.014761);

    INSERT INTO staedte (stadtname, breitengrad, laengengrad) 
    VALUES ('Köln', 50.938056, 6.956944);

    INSERT INTO staedte (stadtname, breitengrad, laengengrad) 
    VALUES ('Krefeld', 51.33262, 6.56238);

    INSERT INTO staedte (stadtname, breitengrad, laengengrad) 
    VALUES ('Leverkusen', 51.033333, 6.983333);

    INSERT INTO staedte (stadtname, breitengrad, laengengrad) 
    VALUES ('Mönchengladbach', 51.19414, 6.43161);
    
    /**
    INSERT INTO staedte (stadtname, breitengrad, laengengrad)
    VALUES ('Mülheim an der Ruhr', 51.2562, 7.1508);

    INSERT INTO staedte (stadtname, breitengrad, laengengrad)
    VALUES ('Oberhausen', 51.2562, 7.1508);

    INSERT INTO staedte (stadtname, breitengrad, laengengrad)
    VALUES ('Remscheid', 51.2562, 7.1508);

    INSERT INTO staedte (stadtname, breitengrad, laengengrad)
    VALUES ('Solingen', 51.2562, 7.1508);

    INSERT INTO staedte (stadtname, breitengrad, laengengrad)
    VALUES ('Wuppertal', 51.2562, 7.1508);
    **/

    DBMS_OUTPUT.PUT_LINE('Tabelle Staedte erfolgreich mit Daten befüllt.');

    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Fehler beim Einfügen: ' || SQLERRM);
END;
/

-- Splitten von Texten 
DECLARE
    v_str VARCHAR2(4000);
BEGIN
    -- CSV-String aus Tabelle laden
    SELECT data
    INTO v_str
    FROM user001.webservice_loads
    WHERE id = 2;

    DBMS_OUTPUT.PUT_LINE('Geladene Daten: ' || v_str);

    -- Split-Logik aus Oracle-Blog (REGEXP_SUBSTR + CONNECT BY)
    FOR rec IN (
        WITH rws AS (
            SELECT v_str AS str FROM dual
        )
    SELECT REGEXP_SUBSTR(
                str,
                '[^,]+',
                1,
                LEVEL
            ) AS value
    FROM rws
    CONNECT BY LEVEL <= LENGTH(str) - LENGTH(REPLACE(str, ',')) + 1
    )
    LOOP
    -- Ergebnis in STAEDTE einfügen
    INSERT INTO staedte (stadtname, breitengrad, laengengrad)
    VALUES (TRIM(rec.value), NULL, NULL);

    DBMS_OUTPUT.PUT_LINE('Eingefügt: ' || TRIM(rec.value));
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('Alle Städte erfolgreich eingefügt.');
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('Kein Datensatz mit ID=2 gefunden.');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Fehler: ' || SQLERRM);
END;
/

