DROP TABLE staedte;


-- Aufgabe 1a)
CREATE TABLE staedte (
    stadt_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stadtname VARCHAR2(100), -- Name der Stadt
    breitengrad NUMBER(10,6) NOT NULL,   -- Einheit: Grad (° Nord/Süd)
    laengengrad NUMBER(10,6) NOT NULL    -- Einheit: Grad (° Ost/West)
);

--Aufgabe 1b)
BEGIN
    INSERT INTO staedte (stadtname, breitengrad, laengengrad) 
    VALUES ('Aachen', 50.775278, 6.083889);

    INSERT INTO staedte (stadtname, breitengrad, laengengrad) 
    VALUES ('Bonn', 50.733992, 7.099814);

    INSERT INTO staedte (stadtname, breitengrad, laengengrad) 
    VALUES ('Düsseldorf', 51.225556, 6.782778);

    INSERT INTO staedte (stadtname, breitengrad, laengengrad) 
    VALUES ('Duisburg', 51.2277, 6.7735);

    INSERT INTO staedte (stadtname, breitengrad, laengengrad) 
    VALUES ('Essen', 51.458069, 7.014761);

    INSERT INTO staedte (stadtname, breitengrad, laengengrad) 
    VALUES ('Köln', 50.938056, 6.956944);

    INSERT INTO staedte (stadtname, breitengrad, laengengrad) 
    VALUES ('Krefeld', 51.33262, 6.56238);

    INSERT INTO staedte (stadtname, breitengrad, laengengrad) 
    VALUES ('Leverkusen', 51.033333, 6.983333);

    INSERT INTO staedte (stadtname, breitengrad, laengengrad) 
    VALUES ('Mönchengladbach', 51.19414, 6.43161);
    
    /**
    INSERT INTO staedte (stadtname, breitengrad, laengengrad)
    VALUES ('Mülheim an der Ruhr', 51.2562, 7.1508);

    INSERT INTO staedte (stadtname, breitengrad, laengengrad)
    VALUES ('Oberhausen', 51.2562, 7.1508);

    INSERT INTO staedte (stadtname, breitengrad, laengengrad)
    VALUES ('Remscheid', 51.2562, 7.1508);

    INSERT INTO staedte (stadtname, breitengrad, laengengrad)
    VALUES ('Solingen', 51.2562, 7.1508);

    INSERT INTO staedte (stadtname, breitengrad, laengengrad)
    VALUES ('Wuppertal', 51.2562, 7.1508);
    **/

    DBMS_OUTPUT.PUT_LINE('Tabelle Staedte erfolgreich mit Daten befüllt.');

    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Fehler beim Einfügen: ' || SQLERRM);
END;
/

-- Splitten von Texten 
WITH rws AS (
    SELECT data AS str
    FROM user001.webservice_loads
    WHERE id = 2
)
SELECT REGEXP_SUBSTR(
        str,
        '[^,]+',
        1,
        LEVEL
    ) AS stadtname
FROM rws
CONNECT BY LEVEL <=
LENGTH(str) - LENGTH(REPLACE(str, ',')) + 1;

