DROP TABLE staedte;


-- Aufgabe 1a)
CREATE TABLE staedte (
    stadt_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stadtname VARCHAR2(100),                -- Name der Stadt
    breitengrad NUMBER(10,6) NOT NULL,      -- Einheit: Grad (° Nord/Süd)
    laengengrad NUMBER(10,6) NOT NULL       -- Einheit: Grad (° Ost/West)
);
/


--Aufgabe 1b)

/** 
Muster:
1. Städte sind durch Punkte (.) getrennt
2. Innerhalb jeder Zeile sind Werte durch Leerzeichen getrennt
3. Jede Stadtzeile hat dasselbe Muster
**/
SELECT data FROM user001.webservice_loads WHERE id=2;
/

/** 
Schreib einen PL/SQL-Block, der diesen Text:
    1. zerlegt (jede Stadt einzeln),
    2. umrechnet (Grad + Minuten → Dezimalgrad),
    3. und einfügt (INSERT in staedte)
Ziel: aus einer langen Zeile viele Einzeldatensätze machen
**/

-- -----------------------------------------------------------------------------------------------------------------
-- VIEW ist keine echte Tabelle, sondern eine gespeicherte SQL-Abfrage, die sich wie eine Tabelle verhält
CREATE OR REPLACE VIEW staedte_row
AS WITH rws AS (    -- ist eine Common Table Expression (CTE)
    -- hier wird eine Zeile Text aus user001.webservice_loads geholt
    SELECT data AS str 
    FROM user001.webservice_loads
    WHERE id = 2
)
-- Split-Logik aus Oracle-Blog (REGEXP_SUBSTR + CONNECT BY)
-- Befehl macht aus langen Textzeile mit mehreren Einträgen -> mehrere Zeilen
SELECT
    TRIM(                               -- entfernt überflüssige Leerzeichen am Anfang und Ende
        REGEXP_SUBSTR(                  -- sucht Teilstrings im Text basierend auf einem Muster
            str,                        -- der gesamte Text (z. B. alle Städtedaten)
            '[^.]+',                    -- Muster: „alle Zeichen außer Punkt“ (also bis zum nächsten Punkt)
            1,                          -- Startposition: beginne beim ersten Zeichen
            LEVEL                       -- gibt an, welches Teilstück gelesen wird
        )
    ) AS value                          -- das Ergebnis wird als Spaltenname "value" ausgegeben
FROM rws                                -- liest aus der temporären CTE "rws" (enthält den langen Originaltext)
CONNECT BY LEVEL <=                     -- Wiederhole die Abfrage n-mal
    LENGTH(str) -                       -- Länge des Originaltexts minus
    LENGTH(REPLACE(str, '.')) + 1;      -- Länge des Texts ohne Punkte → ergibt Anzahl der Punkte + 1
                                        -- so oft wird wiederholt, bis jede Teilzeile (zwischen den Punkten) gelesen ist
/

-------------------------------------------------------------------------------------------------------------------------
DECLARE
    v_line VARCHAR2(1000);   -- ganze Zeile (z. B. '50 56 N 6 57 E Köln')
    n_g NUMBER(10,2);        -- Grad Nord
    n_m NUMBER(10,2);        -- Minuten Nord
    o_g NUMBER(10,2);        -- Grad Ost
    o_m NUMBER(10,2);        -- Minuten Ost
    stadtname VARCHAR2(100); -- Stadtname
BEGIN
    FOR r IN (SELECT value FROM staedte_row) LOOP
        -- Zeilenumbrüche entfernen
        v_line := REPLACE(REPLACE(r.value, CHR(10), ''), CHR(13), '');

        -- Werte aus dem Text schneiden
        -- Beispiel: 50 56 N 6 57 E Köln
        n_g := TO_NUMBER(SUBSTR(v_line, 1, 2));   -- Grad Nord (50)
        n_m := TO_NUMBER(SUBSTR(v_line, 5, 2));   -- Minuten Nord (56)
        o_g := TO_NUMBER(SUBSTR(v_line, 12, 1));  -- Grad Ost (6)
        o_m := TO_NUMBER(SUBSTR(v_line, 15, 2));  -- Minuten Ost (57)
        stadtname := SUBSTR(v_line, 22);          -- Stadtname (Köln)

        -- Umrechnung: Grad + Minuten / 60 = Dezimalgrad
        -- Das kann man zwar einfacher lesen 50° 56′, aber das wird später schwer zu berechnen, deswegen 
        -- wandeln wir es in eine Dezimalzahl wie 50.9333 um
        INSERT INTO staedte (stadtname, breitengrad, laengengrad)
        VALUES (
            stadtname,
            n_g + n_m / 60,  -- Breitengrad als Dezimalzahl
            o_g + o_m / 60   -- Längengrad als Dezimalzahl
        );
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('Daten erfolgreich eingefügt.');

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Fehler: ' || SQLERRM);
END;
/

-- Testen
SELECT * FROM staedte;

