DESCRIBE COUNTRIES
DESCRIBE DEPARTMENTS
DESCRIBE EMPLOYEES
DESCRIBE JOB_HISTORY
DESCRIBE JOBS
DESCRIBE LOCATIONS
DESCRIBE REGIONS

SET ECHO ON

SELECT * FROM COUNTRIES;
SELECT * FROM DEPARTMENTS;
SELECT * FROM EMPLOYEES;
SELECT * FROM JOB_HISTORY;
SELECT * FROM JOBS;
SELECT * FROM LOCATIONS;
SELECT * FROM REGIONS;